version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: haidaqn
    environment:
      MYSQL_ROOT_PASSWORD: 123456x
      MYSQL_DATABASE: ecm_product
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
